# ----------------------------------------------------------------------------------------------------------------------
# 核心配置
# ----------------------------------------------------------------------------------------------------------------------
logging:
  file:
    name: "kse-frontend"
    path: "/var/log"

# ----------------------------------------------------------------------------------------------------------------------
# Carnival
# ----------------------------------------------------------------------------------------------------------------------
carnival:
  openfeign:
    logger-level: full
